language: ruby
rvm:
  - ruby-head
  - 2.2.0
  - 2.1
  - 2.0.0
  - 1.9.3
before_install:
  - rm -f Gemfile.lock  # in order of windows/linux compability
  - export ON_TRAVIS=true  # flag for Travis-CI  
notifications:
  email: false
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: 1.9.3
  fast_finish: true
