language: ruby
sudo: false
rvm:
  - ruby-head
  - 2.2.0
  - 2.1
  - 2.0.0
  - jruby-19mode
  - jruby
  - rbx
  - rbx-2
before_install:
  - rm -f Gemfile.lock  # in order of windows/linux compability
bundler_args: --without development production
cache: bundler
env:
  global:
    - JRUBY_OPTS="-Xcext.enabled=true"
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-19mode
    - rvm: jruby
    - rvm: rbx
    - rvm: rbx-2
  fast_finish: true
notifications:
  email: false
